### ISSUE TITLE
AWS CodePipeline - aws ecr get-login-password ... docker login が失敗する ( pre_build )

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/medium#340]
# buildspec.yml

チュートリアル通りのだいたいこんなやつ

```yaml
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 012345678910.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=012345678910.dkr.ecr.us-west-2.amazonaws.com/hello-world
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
```

# エラー例

```
[Container] 2023/02/08 09:45:48 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin *********.dkr.ecr.ap-northeast-1.amazonaws.com. Reason: exit status 1
```

# 解決

ビルドプロジェクト > ビルドの詳細 > サービスロール

のリンクからIAMでポリシーを許可することで解決した
( *EC2InstanceProfileForImageBuilderECRContainerBuilds* を追加 )

![image](https://user-images.githubusercontent.com/13635059/217496514-6ecbc0eb-060d-4c12-bf3b-384bf04ef405.png)

![image](https://user-images.githubusercontent.com/13635059/217496520-815bde40-ce50-4f23-a189-62407a55cae5.png)

![image](https://user-images.githubusercontent.com/13635059/217496522-3e241e3a-ec60-42a2-99f6-05b5d6f4039d.png)

# チャットメンバー募集

何か質問、悩み事、相談などあればLINEオープンチャットもご利用ください。

https://line.me/ti/g2/eEPltQ6Tzh3pYAZV8JXKZqc7PJ6L0rpm573dcQ

# Twitter

https://twitter.com/YumaInaura
